datetime_cols:
  - customer_churned_at
  - customer_started_at

num_cols: 
  - commission_base
  - commission_xs
  - days_to_churn
  - product_x
  - product_y

cat_cols: 
  - product
  - channel
  - age_bucket
  - operating_system

ohe_cols:
  - is_xs

target_churn: is_churn
target_ltv: months_as_client

train_test_ratio: 0.2
SEED: 42

xgb_parameters:
  n_estimators: [400, 500, 600]
  max_depth: [4, 5, 6]

kfold_parameters:
  k: 6
  n_splits: 5

survival_threshold: 0.7

top_n_features: 5

max_clusters: 10
n_splits: 5

problem_type_classification: Classification
problem_type_regression: Regression